use super::*;
use smtpclient::SmtpBuilder;

#[test]
fn recv_email_local(){

    std::thread::spawn(||{
        main(); 
    });

    let secrets = aml::load("config.aml");

    let smtp_client_builder = SmtpBuilder::new(
        ("127.0.0.1").into(), //host 
        ("25").into(), //port
        ("sender@example.com").into(), //sender
        ("test@example2.com").into(), //recipient
        ("example.com").into() //domain
    );
    smtp_client_builder
        .subject("Testing Email".into())
        .body("This is a body - Generated by builder\nCan I have 한글? 안녕하세요~~".into())
        .auth_plain(secrets.get("password").unwrap().into())
        .display_name("Adam the Rusty".into())
        .send().unwrap();
}


#[test]
fn test_email_struct(){
    let email = Email::new();
    println!("{:?}", email)
}